# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Welcome!
# Description of the Site
description: Praveen here, and this is my portfolio site
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: praveenkrishna0512@gmail.com
facebook_username:
telegram_username: praveeeenk
twitter_username:
instagram_username: pravedino
linkedin_username: praveen-krishna-3ba174207
github_username: praveenkrishna0512
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username: 21vcwcxyohtrunex6rf46t2ja

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Praveen

# Name of the Author
author-name: Praveen Krishna
# URL for the Image of the Author
author-image: assets\images\prof pic 10.jpg
# 60 Words About the Author
author-about: Hello! Praveen here. I am a Computer Science Freshman @ NUS, looking to maximise social impact through my activities.
              I love to envision the different ways in which tech can be used for good.
              My hobbies include hitting up the gym, the dance floor, and of course IDEs.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.linkedin.com/in/praveen-krishna-3ba174207/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
